[build]
  command = "your-build-command-here"
  publish = "your-publish-directory-here"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "cors"
  path = "/*"


[[headers]]
  for = "/"
  [headers.values]
    Access-Control-Allow-Origin = ""
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"