[build]
  command = "npm run build:ssr"
  functions = "netlify/functions"
  publish = "dist/firstwork/browser"

[[plugins]]
package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
